name: Publish to Homebrew

on:
  release:
    types: [published]

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v5
        with:
          token: ${{secrets.HOMEBREW_TOKEN}}
          formula: "spacer"
